title: "Jesse Ford Colter Smith's Blog"
description: "A blog about electronics, woodworking, hacking, and art."
baseurl: ""  # Leave empty for GitHub Pages
url: "https://jessefordcolter.github.io"

# Markdown settings
markdown: kramdown

# Enable plugins for pagination and SEO
plugins:
  - jekyll-seo-tag  # SEO optimization
  - jekyll-paginate  # Pagination for posts

paginate: 5  # Display 5 posts per page
paginate_path: "/page:num/"  # URL path for pagination

# Set the permalink structure to include categories
permalink: /:categories/:title/

# Collections and categories setup
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: post
      categories: general

# Jekyll SEO tag plugin
seo:
  title: "{{ page.title }} | {{ site.title }}"
  description: "{{ site.description }}"
  author: "Jesse Ford Colter Smith"
